[package]
name = "bsl-http1"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[features]
default = []
networkless-fixture = ["dep:bsl-stream-fixture"]

[dependencies]
bsl-stream = { path = "../bsl-stream" }
bsl-stream-fixture = { path = "../bsl-stream-fixture", optional = true }
bsl-tls = { path = "../bsl-tls" }
bsl-vault = { path = "../bsl-vault" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
