[package]
name = "bsl-active-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
bsl-planner = { path = "../bsl-planner" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true
