[package]
name = "bsl-operator"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
bsl-content-analysis = { path = "../bsl-content-analysis" }
bsl-passive-analyzers = { path = "../bsl-passive-analyzers" }
bsl-policy = { path = "../bsl-policy" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
chrono.workspace = true
