[package]
name = "bsl-local-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
bsl-executor = { path = "../bsl-executor" }
bsl-pinned-transport = { path = "../bsl-pinned-transport" }
bsl-transport = { path = "../bsl-transport" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
chrono.workspace = true
bsl-gateway = { path = "../bsl-gateway" }
bsl-policy = { path = "../bsl-policy" }
url.workspace = true
