[package]
name = "nxb-redirect"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
nxb-gateway = { path = "../nxb-gateway" }
nxb-http1 = { path = "../nxb-http1" }
nxb-pinned-transport = { path = "../nxb-pinned-transport" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
chrono.workspace = true
nxb-policy = { path = "../nxb-policy" }
