[package]
name = "bsl-channel-contracts"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
bsl-stream = { path = "../bsl-stream" }
bsl-tls = { path = "../bsl-tls" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true
