[package]
name = "nxb-channel-contracts"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
nxb-stream = { path = "../nxb-stream" }
nxb-tls = { path = "../nxb-tls" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true
