[package]
name = "bsl-http1-fixture"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
bsl-executor = { path = "../bsl-executor" }
bsl-http1 = { path = "../bsl-http1" }
bsl-stream = { path = "../bsl-stream" }
bsl-stream-fixture = { path = "../bsl-stream-fixture" }
bsl-transport = { path = "../bsl-transport" }
serde_json.workspace = true
